AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  sdjustin2 - API Gateway with custom domain for HTTPS
Parameters:
  DomainName: www.sdjustin.com
    Type: String
    Description: The custom domain name for the API (e.g., api.yourdomain.com)
  CertificateArn: arn:aws:acm:us-east-2:533267296255:certificate/fedfce93-f665-48dc-9321-889955ba05de
    Type: String
    Description: The ARN of the ACM certificate for the custom domain
Globals:
  Function:
    Timeout: 300   
Resources:
  # Explicitly define the API Gateway
  CFMLSelectApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        Route53:
          HostedZoneName: !Sub "${DomainName}." # e.g., yourdomain.com.
        EndpointConfiguration: REGIONAL
        SecurityPolicy: TLS_1_2
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "CFMLSelectApi"
        paths:
          "/{proxy+}":
            x-amazon-apigateway-any-method:
              produces: ["application/json"]
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CFMLSelectFunction.Arn}/invocations"
                httpMethod: "POST"
                type: "aws_proxy"
          "/":
            x-amazon-apigateway-any-method:
              produces: ["application/json"]
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CFMLSelectFunction.Arn}/invocations"
                httpMethod: "POST"
                type: "aws_proxy"
  CFMLSelectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.foundeo.fuseless.StreamLambdaHandler
      CodeUri: ./build/distributions/fuseless-template.zip
      Runtime: java11
      Timeout: 300
      MemorySize: 3008
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref CFMLSelectApi
            Path: /{proxy+}
            Method: any
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref CFMLSelectApi
            Path: /
            Method: any
      Environment:
        Variables:
          FELIX_CACHE_BUFSIZE: 16384
          LUCEE_EXTENSIONS: 'B737ABC4-D43F-4D91-8E8E973E37C40D1B;name=cfimage;path=/var/task/extensions/image-extension-2.0.0.29.lex'
          DB_USERNAME: '{{resolve:ssm:/cfml/873_databaseusername:1}}'
          DB_PASSWORD: '{{resolve:ssm:/cfml/873_databasepassword:1}}'
          DB_CONNECTION_STRING: '{{resolve:ssm:/cfml/873_databaseconnectionstring:1}}'             
      VpcConfig:
        SecurityGroupIds: 
          - '{{resolve:ssm:/cfml/873_securitygroupid:1}}'
        SubnetIds: 
          - '{{resolve:ssm:/cfml/873_subnetid1:2}}'
          - '{{resolve:ssm:/cfml/873_subnetid2:2}}'
Outputs:
  CFMLSelectApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${DomainName}/Prod/"
  CFMLSelectFunction:
    Description: "CFML Lambda Function ARN"
    Value: !GetAtt CFMLSelectFunction.Arn
  CFMLSelectFunctionIamRole:
    Description: "Implicit IAM Role created for CFML Select function"
    Value: !GetAtt CFMLSelectFunctionRole.Arn
  CustomDomainName:
    Description: "Custom domain name for the API"
    Value: !Ref DomainName